# Site settings
title: 深藏若虛
email: fntsrlike+blog@gmail.com
description: 史記·卷六十三·老子韓非傳：「良賈深藏若虛，君子盛德，容貌若愚。」
baseurl: "" # the subpath of your site, e.g. /blog/
url: http://blog.fntsr.tw
twitter_username: fntsrlike
github_username:  fntsrlike

# Build settings
markdown: kramdown

# Advanced
timezone: Asia/Taipei
