# Site settings
title: 深藏若虛
email: fntsrlike+blog@gmail.com
description: 史記·卷六十三·老子韓非傳：「良賈深藏若虛，君子盛德，容貌若愚。」
baseurl: "/jekyll" # the subpath of your site, e.g. /blog/
url: http://fntsr.tw/jekyll
twitter_username: fntsrlike
github_username:  fntsrlike

# Build settings
markdown: kramdown

# Advanced
timezone: Asia/Taipei
highlighter: pygments
excerpt_separator: ""   # Workaround for http://blog.slaks.net/2013-08-09/jekyll-tag-was-never-closed

# Assets
vendor: /assets/vendor
